---
version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:235494798709:task-definition/py-task:1"
        LoadBalancerInfo:
          ContainerName: "karthik-y"
          ContainerPort: 5000
