---
version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:535002878565:task-definition/python-task:1"
        LoadBalancerInfo:
          ContainerName: "pythoncontainer"
          ContainerPort: 5000
